services:
  warehouseapp:
    build:
      context: .
    command: bash start-dev.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8083:8084"
      - "5005:5005"
    volumes:
      - .:/warehouse:z
    networks:
      - ecommerce-net
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:4.0.5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: >
      sh -c "rabbitmq-pludins enable rabbitmq_management &&
      rabbitmq-server"
  networks:
    ecommerce-net:
      name: ecommerce-net

networks:
  ecommerce-net:
    name: ecommerce-net
    external: true